libbpf/ci

travis-ci/vmtest/run.sh

This is a port from https://github.com/libbpf/libbpf/pull/352.
> When new eBPF program, map, or attach types are added to the kernel, bpftool needs to be updated in order to support the related features. These updates should add the new types to the code itself, but also to the help messages, documentation, and bash completion. Given that it is easy to omit one of those, a script has been created to attempt to validate that all parts have been consistently updated.
> 
> This new script for bpftool is hosted in the kernel repository, amongst the BPF selftests. But it is not called from the Makefile, and not run along with the other selftests. If it was, all patches updating the BPF UAPI would require the relevant changes in bpftool at the same time, _in the same patches_, which is not …

ci: run script to test bpftool types/options sync

---

custom-workflows/bpf/test.yml

otherwise it will have two runs per change e.g. https://github.com/tsipa/bpf-next/runs/3385170856

This flow should not be triggered on push

---

setup-build-env/action.yml

BPF selftests depend on sys/sdt.h header for defining USDT probes. This
header is coming from systemtap-sdt-devel package, so ensure this
package is installed before selftests are built.
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>

ci: install systemtap-sdt-devel package needed for USDT selftests

---

INDEX

`ethtool` was added to the image. See https://github.com/libbpf/libbpf/pull/488
This change update INDEX file to point to the new image.
```
wget https://libbpf-ci.s3.us-west-1.amazonaws.com/x86_64/libbpf-vmtest-rootfs-2022.04.25.tar.zst
wget https://libbpf-ci.s3-us-west-1.amazonaws.com/x86_64/vmlinuz-5.5.0
rootfs_img=rootfs.img kernel_bzimage=vmlinuz-5.5.0
mkdir rootfs
touch rootfs.img
truncate -s 2G rootfs.img
mkfs.ext4 -q rootfs.img
sudo mount -o loop rootfs.img rootfs
cat ./libbpf-vmtest-rootfs-2022.04.25.tar.zst | sudo tar -C rootfs -I zstd -xvf -
sudo umount rootfs
sudo install  -m 755 -o root -g root  /dev/stdin rootfs/etc/rcS.d/S50-startup <<'EOF'
ethtool -h
cat /etc/issue
EOF
qemu-system-x86_64 -nodefaults  -display none -serial mon:stdio -enable-kvm -m 4G -drive …
```

Update INDEX to reference the latest rootfs image.

---

INDEX

update s390x image from https://github.com/libbpf/libbpf/pull/492
Test: Made sure I did not screw up tabs....
```
cat INDEX| awk -F '\t' '{print $1"**"$2}'
x86_64/libbpf-vmtest-rootfs-2020.09.27.tar.zst**https://libbpf-ci.s3-us-west-1.amazonaws.com/x86_64/libbpf-vmtest-rootfs-2020.09.27.tar.zst
x86_64/vmlinux-4.9.0.zst**https://libbpf-ci.s3-us-west-1.amazonaws.com/x86_64/vmlinux-4.9.0.zst
x86_64/vmlinux-5.5.0.zst**https://libbpf-ci.s3-us-west-1.amazonaws.com/x86_64/vmlinux-5.5.0.zst
x86_64/vmlinuz-5.5.0**https://libbpf-ci.s3-us-west-1.amazonaws.com/x86_64/vmlinuz-5.5.0
x86_64/vmlinuz-4.9.0**https://libbpf-ci.s3-us-west-1.amazonaws.com/x86_64/vmlinuz-4.9.0
s390x/libbpf-vmtest-rootfs-2022.05.09.tar.zst**https://libbpf-ci.s3.us-west-1.amazonaws.com/s390x/libbpf-vmtest-rootfs-2022.05.09.tar.zs …
```

update INDEX to pick up new s390x image from libbpf/libbpf#492

---

setup-build-env/build_pahole.sh

Pahole 1.23 has been released. Looking at the git repository,
CMakeLists.txt already contains DDWARVES_MINOR_VERSION=23. Hence, the
temporary fix we have in place that updates minor version is no longer
necessary or having any effect. Remove it.

Remove DDWARVES_MINOR_VERSION workaround

---

build-linux/build.sh
build-samples/build_samples.sh
build-selftests/build_selftests.sh
helpers.sh

As discussed in an earlier [pull request][pr20] this change introduces a
function for the LLVM parsing logic and uses it to deduplicate the three
copies of it.
[pr20]: https://github.com/libbpf/ci/pull/20#discussion_r929369587

Factor out LLVM version parsing function

---

build-linux/build.sh

So far we have relied on the kernel configuration as checked into the
kernel-patches/vmtest repository. However, this configuration is now
included in upstream Linux [0].
With this change we switch over to using the configuration from there.
[0] https://lore.kernel.org/bpf/165893461358.29339.11641967418379627671.git-patchwork-notify@kernel.org/T/#m2a97b0ea9ef0ddee7a53bbf7919e3f324b233937

Rely on upstream kernel configuration

---

build-linux/build.sh

This change reverts commit 92f123b240be8b5fbebd08c7e5e2460b87e67e09. The
remaining instability in CI (caused by a NULL pointer dereference in the
kernel itself; reported [here]) seems to be caused by changes made as
part of minimizing the kernel configuration.
Let's rely on the non-upstream kernel configuration for now and until we
know which options precisely we should add (and/or fix the bug in
question).
[here]: https://lore.kernel.org/bpf/d8184db7-3247-c75f-7797-d3a5b0488743@huawei.com/T/#m1ea0cf0140edbd60d173f3ad52732db19a48cf2c

Revert "Rely on upstream kernel configuration"

---

helpers.sh
setup-build-env/install_clang.sh

Development on LLVM 16 has started and version 15 is no longer available
in the repository we install it from. Bump the version we use
accordingly.

Bump LLVM version we use to 16

---

build-linux/build.sh

https://github.com/kernel-patches/vmtest/commit/e5a73f5867617c873268914c229edbf8d407bf48
has renamed the kernel configuration in the kernel-patches/vmtest
repository, removing the '-latest' suffix.
As such, there is no need for us to keep attempting to source this file.
Stop doing so.

Stop sourcing -latest kernel config

---

build-selftests/build_selftests.sh

The selftest build is currently redirected to /dev/null. That
potentially makes it hard to understand what is going on. Given that the
UI hides the output by default anyway, but allows for inspection if
necessary, because of the fold makers, let's just emit said output.

Preserve selftest build output

---

get-llvm-version/action.yml
helpers.sh
setup-build-env/install_clang.sh

Whenever development on a new LLVM version starts, earlier versions of
llvm, clang, and lld may seize to exist in distribution snapshot
repositories. For us, that means having to manually bump the version in
three repositories [0][1][2], in a specific order. That's cumbersome to
do and ultimately we probably want a single source of truth as to what
the most recent LLVM version to use is.
This change introduces an action that centralizes this information while
making it available across repository boundaries. We will subsequently
be able to eliminate hardcoded version information in the other two
repositories constituting the BPF CI.
[0] https://github.com/kernel-patches/vmtest/pull/107
[1] https://github.com/libbpf/libbpf/pull/542
[2] https://github.com/libbpf/ci/pull/24

Introduce get-llvm-version action

---

prepare-rootfs/run_vmtest.sh

With upcoming changes we will introduce more "stages" to the CI
pipeline: instead of having basically a single job (though executed in
different configurations), that does everything from installing
dependencies to building to running tests in one go, we'd like to make
building and running of tests (the two longest running parts of the
overall pipeline) separate (but dependent on each other).
Currently, however, at least on s390x runners, that would fail, because
tests are being run in a new container environment where side-effects of
setup steps done earlier are no longer present. Specifically, as part of
the build preparation we updated the apt repository information
and made sure to install the zstd package.
With this change we make sure to repeat both steps as part of the 'test'
stage …

Fix prepare-rootfs action when using separate jobs

---

prepare-rootfs/action.yml
prepare-rootfs/run_vmtest.sh

The path to the file system image used by our invocation of Qemu is
currently hard coded to /tmp/root.img. This constant originates in the
run_vmtest.sh script, but is then hard-coded in other locations as well,
without an obvious connection between the two. That makes it hard to
understand the code.
This change makes the path to the image an explicit input parameter to
the prepare-rootfs action and the run_vmtest.sh script, which will make
it possible to make the input-output relationship more obvious in client
code moving forward.

Make Qemu image path configurable

---

prepare-rootfs/action.yml
prepare-rootfs/run_vmtest.sh

We would like to have the ability to run selftests in parallel as
opposed to fully serial as is currently the case. In order to make that
possible, this change adjusts the `prepare-rootfs` action to accept an
optional argument specifying the test to run and passes it to the
`run_selftests.sh` script that we adjusted already to earlier.

Plumb through test to run

---

prepare-rootfs/action.yml

With both vmtest [0] and libbpf [1] now providing the image-output
argument to the prepare-rootfs action, we no longer need it to have a
default value. Remove it and make the input required.
[0] https://github.com/kernel-patches/vmtest/commit/281b3c8bfdea9748783e18ec2eafa5736525b72f
[1] https://github.com/libbpf/libbpf/commit/69938da6d7748a7b445954a959288b15bf9d8c38

Remove default value for image-output argument

---

run-qemu/action.yml
run-qemu/run.sh

We typically used fully uppercased names for environment variables in
shell scripts. There does not seem to be a good reason for diverging for
$vmlinuz specifically. Rename it.

Uppercase vmlinuz variable

---

run-qemu/action.yml

This change adds the kernel-root argument to the run-qemu action. We
will need this argument once we want to move bpftool checks into the
actual selftest run job, as opposed to having them happen in the
unrelated prepare-rootfs. We need a default value while all "callers"
are being transitioned to providing this argument. The KERNEL_ROOT
variable that we set based on it is not currently unused (will come with
subsequent changes).

Add kernel-root argument to run-qemu action

---

prepare-rootfs/action.yml

Having default arguments on an action should probably be avoided if
possible. For one, it's confusing to see something being "required" but
having a default value, but if not explicitly mentioned on the call
site, it's also unnecessarily hard to understand what is going on.
With https://github.com/libbpf/libbpf/pull/570 merged we no longer need
default values for two arguments to the prepare-rootfs action, as all
call sites explicitly provide values. Hence, remove them.

Remove default arguments from prepare-rootfs action

---

prepare-rootfs/action.yml
prepare-rootfs/run.sh
run-qemu/run.sh

Currently the bpftool tests are run as part of the prepare-rootfs
action. That's counter-intuitive, as running a test has nothing
"preparational" to it. That in turn causes confusion with users that are
trying to debug failures of said tests: they have no idea how to find
the logs in question, because success/failure is reported as part of a
later action.
This change moves the running of the bpftool tests into the run-qemu
action, which is where selftest results are reported as well. As such,
we remove the need for an implicit file with a hard coded path being
used for communication between these two steps, and of course the
confusion for users is fixed as well.
It is still sub-optimal because we are running this test for every other
selftest run, but that is unchanged from before. The …

Move bpftool check into run-qemu action

---

run-qemu/run.sh

Quentin clarified why we are running bpftool checks only on LATEST and not older kernels: https://github.com/libbpf/ci/pull/37#discussion_r967732472
Add a comment to enshrine that thinking into the code.

Add comment about bpftool checks running only on LATEST

---

INDEX

Built with: `sudo ./mkrootfs_debian.sh --arch=arm64`

Add arm64 rootfs

---

build-linux/build.sh
prepare-rootfs/action.yml
prepare-rootfs/run.sh

With
https://github.com/libbpf/libbpf/commit/bfdf7653e0c46127bb889a5f73eea803bea1d81a and
https://github.com/kernel-patches/vmtest/commit/1656bf12ea2a6b29f3ac5fe274699ef800ab98af we have adjusted both clients of this repository to store their CI related functionality in the ci/ directory, as opposed to travis-ci/. Thus, we can now adjust the references to the latter here as well, and subsequently remove the symbolic links introduced in both repositories as an intermediate solution preventing breakage.

Remove references to travis-ci/ directory

---

run-qemu/action.yml

It seems that the tools are not available within the runner anymore:
https://github.com/kernel-patches/rcu-rc/actions/runs/3222971213/jobs/5272953366#step:5:30
https://gist.github.com/chantra/c456efce54e3477984fde89eb0c9c939#file-runner-log-L743
This change makes sure qemu for the different architectures we may support is installed.
After this change, run-qemu action was able to successfully start the VM.

ci: Install qemu tools before running qemu

---

INDEX

Those images are all debian based and have an updated init script that symlinks /dev/fd to /proc/self/fd per https://github.com/libbpf/ci/pull/44

ci: Update images for all architectures

---

setup-build-env/install_clang.sh

Put the repository in /etc/apt/sources.list.d/llvm.list instead of appending it to /etc/apt/sources.list.
This avoid having the repository duplicated multiple times.
While at it, switch from HTTP to HTTPS.

Add LLVM repo in a separate file

---

run-qemu/run.sh

The qemu parameters where tested as part of https://github.com/kernel-patches/rcu-rc/actions/runs/3193882128/jobs/5213462935
The `kvm_accel` values are very much a guess. This was only tested on AWS graviton host where kvm is not available.

Add switch case to be able to run arm64 images in qemu

---

get-llvm-version/action.yml

set-output is being deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
the new recommended way is to write the name/valuer pain in
GITHUB_OUTPUT env file.
Fixes #47

actions: Use new method to set output variables

---

INDEX

Those images were built with both #56 and #57 applied.
The former fixes building the rootfs for a foregin architecture and should not result in any material changes in the image.
The latter fixes an initscript to work when run with busybox'sh.

rootfs: Fix init script errors #54

---

rootfs/mkrootfs_tweak.sh

The init scripts are run using busybox's `sh` which behaves differently than bash.
More specifically:
```
root@(none) /]# busybox sh
/ # [[ -z $(/bin/mount -t devtmpfs) ]]
sh: on: unknown operand
/ # [[ -a /dev/fd ]]
sh: /dev/fd: unknown operand
```
This change fixes the first issue by wrapping the command substitution in quotes, and changes `-a` test to `e` which seem to do the same thing.
Busybox documentation does not seem to have any reference about that.
With this change and an updated rootfs, the errors do not happen anymore:
```
+ [ -x /etc/rcS.d/S10-mount ]
+ /etc/rcS.d/S10-mount
+ /bin/mount proc /proc -t proc
+ /bin/mount -t devtmpfs
+ [[ -z devtmpfs on /dev type devtmpfs (rw,relatime,size=3029136k,nr_inodes=757284,mode=755) ]]
+ /bin/mount sysfs /sys -t sysfs
+ /bin/mount bpffs …
```

rootfs: Make rootfs init script work with busybox

---

rootfs/mkrootfs_debian.sh

An update in upstream cause a binary on the foreign platform to be
executed, which in turned caused the rootfs creation to fail with
something like:
```
chroot: failed to run command '/bin/true': Exec format error
```
`debootstrap` can handle that natively by building the image in 2 steps.
1) download the packages, verify, and extract them inside the chroot
2) running a second stage that unpack and configure them.
Before the second stage, we copy `qemu-${foreign_arch}-static` into the
chroot, allowing the native binaries to run properly.
After this fix, the rootfs images could be built.
Fixed #55

rootfs: fix foreign arch

---

.github/workflows/lint.yaml
helpers.sh
prepare-rootfs/run.sh

This adds a GitHub action which runs a shell linter on all the .sh files.
ludeeus/action-shellcheck is just an action which relies on
https://github.com/koalaman/shellcheck which is a well known linter.
```bash
~/src/libbpf-ci$ find -type f -name '*.sh' |xargs shellcheck -S error
~/src/libbpf-ci$ echo $?
0
```

add shell linter

---

run-qemu/action.yml
run-qemu/run.sh

On aarch64 and x86_64, qemu will use the number of CPU available on the host. This change allow putting an upper-bound to this value by setting the `CPU_MAX` env variable.
If not specified, the value returned by `nproc` will be used.

run-qemu: Allow setting the maximum number of CPU to allocate to qemu

---

patch-kernel/patch_kernel.sh

This change prepares the `patch-kernel` action for the application of patches with the extension `.patch`, in addition to `.diff`. The need to rename patches to sport the `.diff` extension has repeatedly been shown to be a difficult thing to remember.
See https://github.com/kernel-patches/vmtest/issues/160 for additional technical details.

Honor patches with .patch extension

---

build-linux/action.yml
build-linux/build.sh
build-samples/action.yml
build-samples/build_samples.sh
build-selftests/action.yml
build-selftests/build_selftests.sh
helpers.sh

Currently, the make jobs are spawn 4*nproc jobs. When running a single runner in a VM, that is fine, but when we have a physical machine running 10+ runners, we end up having 4k processes building at the same time.
This change will allow capping the number of jobs spawned by make to something reasonable for both the 1 runner per VM use case and the multiple runners per host use case.

build: Add environment variable to pin the maximum number of processes to be used by make

---

build-samples/action.yml
build-selftests/action.yml
prepare-rootfs/action.yml
prepare-rootfs/run.sh

With https://github.com/libbpf/libbpf/pull/610 and https://github.com/kernel-patches/vmtest/pull/164 merged all clients of the actions provided by this repository provide the now necessary `kbuild_output` argument and none is using `vmlinux_btf` anymore.

Remove deprecated options and other transitory functionality

---

run-qemu/action.yml
run-qemu/run.sh

Historically, we build a VM for each individual tests we wanted to run. At the end of the day, all tests are available within the VM and it is just a matter of what we did put in our init script.
With kernel-patches/vmtest#139 we can now pass the test to run as a command line argument at boot time. So, the run-qemu step will need to provide that test name.
tested with an unmodified kernel-patches/vmtest: https://github.com/kernel-patches/vmtest/pull/171/checks
and a modified one (e.g building the rootfs vm after building the kernel and providing the test on the boot command):  https://github.com/kernel-patches/vmtest/actions/runs/3432974206/jobs/5723083313

Allow passing the tests to run as an argument to qemu

---

ansible/roles/qemu-user-static/tasks/main.yml

We need qemu-user-static.service to be started once to set up binfmt... Currently, this is set as a "oneshot" service, which runs and then is done.
The problem is that we have a dependency from the runners to `qemu-user-static`. When the runner restarts, `qemu-user-static` is not "active" (but "inactive/dead" instead), so it starts it. Because we use `--reset` in `qemu-user-static`, there is a time window when binaries from a foreign architecture won't be handled properly. Possibly in the middle of a runner run.
This change adds `RemainAfterExit=yes` to `qemu-user-static`, which has the effect of keeping the unit as "active" so it does not restart it.
This was tried on `bpf-ci-runner-s390x-5` and could confirm that when a runner restarted, the `qemu-user-static` service was not restarted. …

ansible: Prevent qemu-user-static from being reloaded on runner restart

---

ansible/playbook.yml
ansible/roles/base/tasks/setup-RedHat.yml
ansible/roles/base/vars/RedHat.yml
ansible/roles/runner/defaults/main.yml
ansible/roles/runner/files/app_token.sh
ansible/roles/runner/files/gh_token_generator.sh
ansible/roles/runner/handlers/main.yml
ansible/roles/runner/tasks/main-generic.yml

This stack does quite a few things:
- allow setting runners with ansible on AWS
-  use kvm when pssible (bare-metal) and also allow setting multiple runners per repo
- add architecture in the runner label see kernel-patches/vmtest#162 for context.
- add support to run runners using a GH app instead of a GH user, this helps runners not being impacted/impact rate limiting
- add a runner prefix

Ansible for AWS runners

---

build-linux/action.yml
build-samples/action.yml
build-selftests/action.yml
prepare-rootfs/action.yml

At this point, there is no reason to build without KBUILD_OUTPUT specified: maintaining additional code paths that build that way is just a burden and there is no benefit of building within the source tree versus outside of it.
Hence, this change proposes making the kbuild-output argument to the various actions mandatory. It's already provided by all clients, so there is no effective change.

Make kbuild-output input required in all actions

---

build-linux/build.sh

`diff(1)` exits with 0 if two files are equal and 1 if they are not. That means our conditional logic is inverse of what it should be. Make sure to always update the config we use by swapping the branches.

Interpret `diff(1)` exit code correctly

---

build-linux/build.sh

The `build-linux` action conditionally updates the kernel config to use if it changed. It's generally useful to be able to see what exactly has changed. For example, the (expanded) configuration contains the compiler version and given that we install the newest clang snapshot on each run we may end up with a new compiler version compared to the one that created the build artifacts and  that forces a full rebuild. It's generally non-obvious when that happens and so printing a diff of the two configs can help better understand behavior, should the need arise.

Print diff when updating kernel config to use

---

helpers.sh

Currently, bpf CI is unable to locate llvm-16 on
aarch64/gcc, aarch64/llvm-16, and s390x/gcc [0].
This change upgrades the default llvm version to 17.
[0] https://github.com/kernel-patches/bpf/actions/runs/4040302668
Signed-off by: Joanne Koong <joannekoong@gmail.com>

Upgrade default llvm version to version 17

---

ansible/roles/qemu-user-static/tasks/main.yml

`multiarch/qemu-user-static` does not support hosts other than x86_64.
`aptman/qus` does. The command syntax is slightly different though.
This change update the systemd resource to:
- [reset](https://github.com/dbhi/qus#reset) the registered format first.
- load all possible architectures persistently
To test, I confirmed that after using this new container, we could still run x86_64 containers in s390x hosts:
Before:
```
linux1@bpf-ci-runner-s390x-2:~$ sudo docker exec -ti 112b682130e9 bash
root@112b682130e9:/actions-runner# /usr/x86_64-linux-gnu/bin/ls
_diag  bin  config.sh  env.sh  externals  run-helper.cmd.template
run-helper.sh.template  run.sh  safe_sleep.sh  svc.sh
```
Updated systemd resource and restarted it:
```
linux1@bpf-ci-runner-s390x-2:~$ sudo systemctl status …
```

[s390x] Use `aptman/qus` instead of `multiarch/qemu-user-static`

---

helpers.sh
setup-build-env/install_clang.sh

This change get us back onto llvm-16 by default as it seemsthat currently, qemu VMs are failing to boot when the kernel is built with llvm 17, it is very likely related to
https://github.com/ClangBuiltLinux/linux/issues/1800 .
Because of the layout of LLVM's apt repo, unless the version is the latest they distribute, the repository distro need to use the version number as suffix.

default to llvm 16

---

setup-build-env/build_pahole.sh

The action has those 2 env var documented, but they were either not used, or statically set in the script. Fix it, this way we can set custom repo/revision when invoking the action.
Testing:
Ran a kernel-patches/bpf test against this branch with the action variable set to
```
pahole: b53d430aeab416e74dd394d646a9e9b21dc7a324
```
which resulted in the following logs.
```
Run export PAHOLE_BRANCH=b53d430aeab416e74dd394d646a9e9b21dc7a324
export PAHOLE_BRANCH=b53d430aeab416e74dd394d646a9e9b21dc7a324
export PAHOLE_ORIGIN=https://git.kernel.org/pub/scm/devel/pahole/pahole.git
${GITHUB_ACTION_PATH}/build_pahole.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
KERNEL: LATEST
REPO_ROOT: /tmp/work/bpf/bpf
REPO_PATH:
KBUILD_OUTPUT: kbuild-output/
build_pahole - Building pahole
Hit:1 …
```

[build_pahole] Use PAHOLE_{BRANCH,ORIGIN} from env, or set to defaults

---

helpers.sh

llvm 16 issues seems fixed and using llvm 16 as the default caused arm64 and s390x failure with the following error message:
The following packages have unmet dependencies:
clang-16 : Depends: libclang-common-16-dev (= 1:16.0.0~++20230222063320+4c0da2726e7f-1~exp1~20230222063432.36) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
clang install failed
Error: Process completed with exit code 1.
let us move to llvm 17.

default to llvm 17

---

helpers.sh

We are still impacted by https://github.com/llvm/llvm-project/issues/60128
I tested manually that version 16 does install on all archs

revert to llvm-16

---

build-linux/action.yml
build-linux/build.sh
build-samples/action.yml
build-samples/build_samples.sh
build-selftests/action.yml
build-selftests/build_selftests.sh
helpers.sh
setup-build-env/action.yml
setup-build-env/install_clang.sh

Since we always build BPF programs with clang, ci also installs llvm when inputs.toolchain is gcc. llvm_version(). Instead of parsing llvm version from inputs.toolchain, add a separate input field of llvm-version.

Add inputs.llvm-version

---

run-qemu/run.sh

This change makes the qemu action consume the report generated by test_progs (introduced in kernel-patches/vmtest#207) and generates github annotations [0] of the summary as well as the failing tests. It also generates a summary of the job [1].
The end goal is to provide an easier way for people to directly access the tests that failed instead of having to scroll through pages of logs.
[0] https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
[1] https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

[run-qemu] consume test_progs json report

---

run-qemu/action.yml
run-qemu/run.sh

Add capability to extract contents of /command_output/ directory from the qemu disk image after qemu execution. This is useful when there is a need to extract multiple result files after tests run.
To use this specify the `output-dir` parameter for the action, e.g.:
```yaml
- name: Run veristat
uses: eddyz87/libbpf-ci/run-qemu@main
timeout-minutes: 10
with:
arch: x86_64
img: '/tmp/root.img'
vmlinuz: '${{ github.workspace }}/vmlinuz'
kernel-root: '.'
max-cpu: 8
kernel-test: run_veristat
output-dir: '${{ github.workspace }}'   # <--- here
```

[run-qemu] Add 'output_dir' action parameter

---

build-selftests/build_selftests.sh

Cleaning selftests is useful in case if cached kernel build artifacts contain build results for selftests.
---
For the context:
I'm currently working on a BPI CI job that executes veristat tool for both push and pull_request events:
- for push in order to obtain baseline performance data;
- for pull_request in order to compare branch performance data with baseline performance data.
The veristat is built with selftests and uses some selftest .bpf.o binary files as an input.
Currently selftests are not built on push, but this would have to change.
Which means that cached incremental kernel build artifacts might now contain selftest binary files.
I'd like to add the clean action to selftests compilation to avoid any potential issues with stale selftest binary files when pull_request event is …

[build-selftests] Clean selftests before building them

---

ansible/roles/qemu-user-static/defaults/main.yml
ansible/roles/qemu-user-static/tasks/main.yml

We have had issue with the latest tag on newly provisioned s390x machines. More specifically some x86_64 command would fails while some other were not. The exact failure is yet TBD, but through troubleshooting and narrowing down the scope of the issue, it appears to have been a regression with the latest container version of aptman/qus, which is currently 7.2.
This pins the container to the debian version of the 7.1 release.
Test plan:
- run using version d7.1: https://github.com/chantra/gh_runner_tests/actions/runs/4802032141/attempts/5 (succeed)
- run using version d7.2: https://github.com/chantra/gh_runner_tests/actions/runs/4802032141/attempts/6 (failed)

[ansible] force aptman/qus with tag d7.1

---

build-selftests/build_selftests.sh

Fixes BPF CI selftest build after 9fc96c7c19df ("selftests: error out if kernel header files are not yet built").
Link: https://lore.kernel.org/lkml/11b94ce7-d7e3-1935-307b-5a0a0f32739f@collabora.com

[build-selftests] Run make headers before building selftests

---

rootfs/mkrootfs_debian.sh

When building rootfs, we install `busybox`.
In Ubuntu, this is hosted under the `universe` component: https://packages.ubuntu.com/focal/busybox
We can specify which component to use with debootstrap. While Debian does not have a universe component, it handles it just fine so we do not need to special case Debian vs Ubuntu.
Test Plan:
Successfully built rootfs for focal and bullseye:
```
sudo ./mkrootfs_debian.sh  --distro bullseye
sudo ./mkrootfs_debian.sh  --distro focal
```

rootfs: Support building Ubuntu rootfs

---

build-linux/build.sh

In preparation of landing v2 of https://lore.kernel.org/bpf/ZTxaRT8AXCNXYmRd@surya/T/#t
Include config.vm files, which in the future will include VM related kernel configs

build-kernel: Add selftests/bpf/config.vm to the list of config files

---

helpers.sh

Bump default clang to 17, latest to 18.

ci: bump clang versions

---

rootfs/Makefile
rootfs/mkrootfs_debian.sh

The usr/share/dpkg/cputable contains mapping ppc64el->powerpc64le, so mkrootfs_debian.sh does lookup with qemu-powerpc64le-static, which is incorrect.

Debian-Gnu name lookup issue for ppc64el

---

ansible/roles/runner/defaults/main.yml
ansible/roles/runner/tasks/main.yml

Currently, the only option passed to tmpfs is `exec` so tmpfs is mounted with "exec" option.
We may need to pass extra options on some runners, like setting the size of tmpfs for instance (docker seems to default to 50% of the host memory), and only on specific hosts, so we need this to be somwhat configurable.
Add a new variable `runner_tmpfs_options` which defaults to `['exec']` and can be overridden at the host/group level.
Test, after setting a host to use:
```
runner_tmpfs_options:
- exec
- size=12G
```
running ansible in dry-run mode:
```
--- before: /etc/systemd/system/actions-runner-kernel-patches@.service
+++ after:
/home/chantra/.ansible/tmp/ansible-local-3819115bni8m1fy/tmp65ktafym
@@ -15,7 +15,7 @@
--health-cmd='(ss -ntp -H dport = :443 | grep -q ESTAB) ||
exit 1' \ …
```

ansible: Allow passing tmpfs options

---

ansible/roles/runner/tasks/main.yml

Amazon Linux 2 has python'ssl module built using openssl 1.0.X.
urllib3>=2.0 requires an ssl module built against openssl 1.1.1+
This change forces urllib3<2.0 so ansible can successfully run the GHCR login step, or would otherwise fail with:
```
TASK [runner : Docker GHCR login] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: urllib3 v2.0 only …
```

ansible: Force urllib3 to version <2.0

---

helpers.sh

From https://apt.llvm.org/
> Jan 25th 2024 - Snapshot becomes 19, branch 18 created
Becuase of how the repositories are layed out, we need to update this value to latest be able to build the right repository URL.

helpers: update latest clang version to 19

---

.github/workflows/lint.yaml
.github/workflows/scripts_tests.yml

v3 depends on nodejs16 which is being deprecated. Upgrade to v4.

actions: Upgrade checkout action to v4

---

ansible/playbook.yml

We used to only run this role on s390x (because it needs it to be able to run x86 actions-runner on s390x).
I am planning to also leverage this for some cross-compilation work where some step unfortunately need to be able to run a binary in the target format.
Test:
```
ansible-playbook -i ~/inventory.yml ./playbook.yml   --limit aws -t qemu
```

ansible: Run qemu-static-user on all hosts

---

build-linux/build.sh
build-samples/action.yml
build-samples/build_samples.sh
build-selftests/action.yml
build-selftests/build_selftests.sh
helpers.sh
setup-build-env/action.yml
setup-build-env/install_cross_compilation_toolchain.sh

This adds handling of a required `arch` parameter.
setup-build-env, build-linux, build-sample, build-selftests are made to handle this input and set the `ARCH` variable when calling `make` to what is expected by Linux build system.
If the `inputs.arch` is different than the host arch, `CROSS_COMPILE` variable will be set to the right toolchain.
`setup-build-env` is also modified to install the corresponding target libraries.

cross-compilation: make libbpf/ci cross-compilation aware

---

ansible/roles/base/tasks/setup-Debian.yml

Fresh Ubuntu installs don't have auditd.

ansible: don't disable auditd if the package is not installed

---

run-vmtest/action.yml

vmtest 0.12.0 was [released](https://github.com/danobi/vmtest/releases/tag/v0.12.0) and contains all the features that were available from my personal fork.

ci: update vmtest to latest release

---

run-vmtest/action.yml

We were seeing permission issues on the kernel-patches/bpf-rc repo like this:
Run libbpf/ci/run-vmtest@main
Run BUILDDIR=$(realpath kbuild-output)
Run curl -L https://github.com/chantra/danobi-vmtest/releases/download/v2.2.0/vmtest-$(uname -m) > /usr/bin/vmtest && chmod 755 /usr/bin/vmtest
/home/runner/work/_temp/14c6d06a-568f-4cef-8b61-a2096f0485ed.sh: line 1: /usr/bin/vmtest: Permission denied
This is b/c kernel-patches/bpf runs on self-hosted runners where actions run as root. However, kernel-patches/bpf-ci runs on managed runners where actions are not given root by default.
Fix by ensuring root in both environments.

ci: Download vmtest binary as root

---

run-vmtest/action.yml

For GH managed runners, KVM is generally available, but we need to configure it so that non-root users can use it. This shouldn't affect the self-hosted runners where we are already root.

run-vmtest: Configure root-less usage of KVM

---

get-linux-source/checkout_latest_kernel.sh

Konstantin Ryabitsev started blocking requests to download kernel source code snapshots by SHA, generally speaking. For BPF CI, we'll have to use a special User-Agent string to make it work again.

ci: pass special User-Agent string when downloading kernel sources snapshot

---

helpers.sh
setup-build-env/install_clang.sh

If no lsb-release file is available, default to `noble`

ci: Install llvm repo matching the running distro

---

INDEX
rootfs/Makefile
rootfs/mkrootfs_debian.sh

* change rootfs script to build Ubuntu Noble instead of Debian Bullseye
* Update INDEX to use newly built Ubuntu noble rootfs

Use Ubuntu 24.04 rootfs

---

build-selftests/build_selftests.sh
setup-build-env/install_clang.sh

Recently kernel BPF selftests gained an optional dependency on LLVM development libraries [1] in order to support tests that disassemble jit produced code. When necessary dependencies are not available such tests are skipped.
This commit adds LLVM development libraries to the build environment, thus enabling jit disassembly tests on the CI.
[1] https://lore.kernel.org/bpf/20240823080644.263943-1-eddyz87@gmail.com/

setup-build-env: install llvm development package

---

rootfs/Makefile

@chantra Hi Manu, Hope all is well!
Currently vmtest in bpf selftests already supports riscv64 [0]. Although we also support local rootfs images, for development convenience and subsequent BPF CI support, let us support online riscv64 rootfs image.
Currently I made a commit to add the riscv64 architecture to the rootfs Makefile, but because I don’t have permission, I can’t continue to push the riscv64 rootfs image to the BPF CI Amazon server. Could you help to deal with this?
Link: https://lore.kernel.org/all/20240905081401.1894789-1-pulehui@huaweicloud.com [0]

rootfs: Add riscv64 arch support

---

ansible/roles/runner/defaults/main.yml
ansible/roles/runner/tasks/main.yml

This contains a couple of steps:
1. Add the possibility to override on a per runner basis the value of DOCKER_TAG by setting its value in /etc/action-runner/runner_unit-\d\d.env
2. make the containers advertise a new docker-{distro}-main instead of docker-main . Current actions are looking for tag docker-main, so by using this new value, the containers won't be picked up
3. change the value of DOCKER_TAG in /etc/action-runner/runner_unit.env This will make ALL container pick the ubuntu noble container version, and should be deployed only once all actions are running on ubuntu noble.

Switch containers to use Ubuntu noble

---

.github/scripts/tar-artifact.sh
.github/workflows/kernel-build.yml
build-linux/build.sh
build-scx-selftests/README.md
build-scx-selftests/action.yml
build-scx-selftests/build.sh
build-selftests/build_selftests.sh

Add `build-scx-selftests` action. This action will build `tools/testsing/selftests/sched_ext` binaries, given kbuild-output and toolchain parameters passed to the action.
The action and its build script are very similar to `build-selftests`. Build scipt is simplified somewhat.
Action inputs are different:
* `repo-root` is a new required parameter, because we don't want to rely on the assuption that `$REPO_ROOT` == `github.workspace`
* `kernel` is removed: it controled the location of `vmlinux.h`, but it is generated from the `$KBUILD_OUTPUT/vmlinux`, and I don't think we need to be able to customize it (at least not yet)
* https://github.com/kernel-patches/bpf/blob/bpf-next_base/tools/testing/selftests/sched_ext/Makefile#L125-L131
* …

Add build-scx-selftests action

---

setup-build-env/action.yml

sched-ext selftests link against zstd. It currently fails with the following linker error:
rc/tools/testing/selftests/sched_ext/build/obj/sched_ext/test_example.o -lelf -lz -lpthread -lzstd
/usr/bin/ld: cannot find -lzstd
collect2: error: ld returned 1 exit status
Fix by installing zstd-dev package.

setup-build-env: Install libzstd-dev

---

run-vmtest/run-bpf-selftests.sh

test -f <file> && <command> is not exactly what we want: it returns non-0 exit code if file does not exists.
Replace them with an explicit if statement.
Example failure: https://github.com/libbpf/libbpf/actions/runs/12794559630/job/35669958975

run-vmtest: fixes in run-bpf-selftests.sh

---

.github/workflows/gcc-bpf.yml
.github/workflows/kernel-build-test.yml
.github/workflows/kernel-build.yml

In order to test selftests/bpf build with GCC BPF, the latest snapshot of GCC BPF compiler has to built from source.
We don't want this to be a dependency for all the test runners, so
introduce a separate gcc-bpf workflow that executes the following:
* checkout Linux source tree and patch it (as in kernel-build)
* download relevant artifacts with the KBUILD_OUTPUT objects (as in
kernel-test)
* build/download GCC BPF compiler
* build selftests/bpf/test_progs-bpf_gcc runner, hence the test BPF
objects built with GCC
The test_progs-bpf_gcc runner is not executed on BPF CI yet [1], so successful selftests build is a successful job run.
[1] https://lore.kernel.org/bpf/87bjw6qpje.fsf@oracle.com/

GCC BPF: factor out into a separate job

---

.github/workflows/kernel-test.yml
run-vmtest/action.yml
run-vmtest/run-bpf-selftests.sh
setup-build-env/action.yml

Traffic monitoring was add to the selftests/bpf[0] to debug some flaky test cases. Enable this in CI by building selftests with libpcap, installing libpcap in the test environment and finally turn it on when running the test.
[0] https://lore.kernel.org/bpf/20240815053254.470944-1-thinker.li@gmail.com/

Enable traffic monitoring to debug flaky selftests

---

setup-build-env/action.yml

Install pkg-config in setup-build-env explicitly so that we can build bpf selftests with traffic monitor without depending on the runner. Currently, s390 runner image does not include pkg-config required by bpf selftests traffic monitor. During compile time, the makefile uses pkg-config to check if libpcap is installed and determines if traffic monitoring feature will be compiled into test_progs.

setup-build-env: Install pkg-config for bpf selftests traffic monitoring

---

build-bpf-gcc/latest-snapshots.sh

Latest binutils snapshot is fetched from:
snapshots.sourceware.org/binutils/trunk/latest/src/sha512.sum
There was an unnecessary grep filter on the tarball name, which caused a script failure when it changed.
Simply take the name of the tarball from the checksum as is instead.

build-bpf-gcc: fix how binutils snapshot is identified

---

.github/workflows/kernel-test.yml
run-vmtest/run-bpf-selftests.sh

Use TEST_PROGS_TRAFFIC_MONITOR env variable to control whether to enable traffic monitor in test_progs. It depends on selftests being built with libpcap-dev.

run-vmtest: conditionally pass -m to test_progs

---

.github/workflows/gcc-bpf.yml
get-linux-source/checkout_latest_kernel.sh

Recently proof-of-work proxy was rolled out for git.kernel.org, which prevents wget of the bpf-next snapshots.
This lead to failures of get-linux-source action:
* https://github.com/kernel-patches/vmtest/actions/runs/14313967784/job/40115985369
* https://github.com/libbpf/libbpf/actions/runs/14316467048/job/40123652831
Simplify the download script to always run git init + git fetch sequence.
[1] https://social.kernel.org/notice/AsgziNL6zgmdbta3lY

get-linux-source: always do git fetch

---

setup-build-env/install_cross_compilation_toolchain.sh

The downgrade helped mitigate package conflicts between linux-libc-dev:amd64 and s390x packages.
Revert the downgrade command.

setup-build-env: do not downgrade linux-libc-dev

---

setup-build-env/action.yml
setup-build-env/build_pahole.sh
setup-build-env/install_clang.sh
setup-build-env/install_cross_compilation_toolchain.sh
setup-build-env/install_packages.sh

Refactor setup-build-env to accept optional gcc-version action input
to control what version of GCC is installed.
Refactor "setup environment" step into a separate install_packages.sh
script.
Simplify install_clang.sh by utilizing officially distributed
installation script [1].
Use update-alternatives to make sure the specified version of GCC is
the system default, when installed via setup-build-env action.
[1] https://apt.llvm.org/

setup-build-env: configurable GCC version

---

ansible/roles/runner/tasks/main.yml

BPF CI runners went down recently due to a problem caused by "Runner not found" error returned from a github broker service [1].
It appears that this error may be triggered by the fact that runner names are reused for "different" runners from the perspective of github. In BPF CI we use ephemeral runners which re-register every time a corresponding runner container is restarted.
Whatever the root cause, a working mitigation is to use unique runner names. Fortunately, entrypoint.sh [1] already has the logic of generating a random suffix, and we only need to set relevant environment variables.
Additionally, set RestartPreventExitStatus=199 in the runner systemd service to prevent error looping in case we run out of tokens [2].
[1] https://github.com/myoung34/docker-github-actions-runner/blob/ …

Add randomized suffix to runner names

---

ci/diffs/20250602-0001-selftests-bpf-Fix-bpf-selftest-build-error.patch
ci/diffs/20250602-0002-selftests-bpf-Fix-selftest-btf_tag-btf_type_tag_perc.patch
ci/diffs/20250602-0003-perf-Fix-the-throttle-error-of-some-clock-events.patch
run-vmtest/action.yml
run-vmtest/install-dependencies.sh
setup-build-env/install_clang.sh
setup-build-env/install_packages.sh

BPF CI self-hosted runner docker images moved to using setup-build-env scripts at build time [1]. Consolidate the list of packages to install in the action script.

setup-build-env: consolidate package dependencies

---

build-scx-scheds/install-dependencies.sh

It turns out github-hosted runners have pipx installed by default, and PIPX_BIN_DIR.
We still want pipx, meson and ninja to be the same between self-hosted and github-hosted runners, so just make sure PIPX_BIN_DIR is right before trying to copy the symlinks.

build-scx-scheds: check for PIPX_BIN_DIR

---

setup-build-env/install_packages.sh

xxd is used to generate a C header from a verification certificate (DER encoded) which is used to test BPF signing infrastructure in selftests.

Add xxd to the base CI debian image
